# Generated by Django 5.0.2 on 2024-03-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_organization_alter_llmconfig_api_key_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="api_id",
            field=models.CharField(
                default="org-587efd57f01947ceacb1f3e4caafb89d",
                editable=False,
                max_length=40,
            ),
            preserve_default=False,
        ),
    ]
