# Generated by Django 5.0.3 on 2024-03-27 09:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_organization_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llmconfig',
            name='user',
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='api_key_name',
            field=models.CharField(default='test key', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.organization'),
            preserve_default=False,
        ),
    ]
