# Generated by Django 5.0.3 on 2024-03-27 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_llmconfig_user_llmconfig_api_key_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LLMConfig',
            new_name='LLMAPIKey',
        ),
    ]
