# Generated by Django 5.0.3 on 2024-03-27 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_llmconfig_llmapikey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='llmapikey',
            old_name='created_date',
            new_name='create_date',
        ),
    ]
