# Generated by Django 5.0.3 on 2024-04-01 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_created_date_llmapikey_create_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LLMAPIKey',
        ),
    ]
