# Generated by Django 5.0.2 on 2024-03-03 11:48

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("genai_app", "0003_promptpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptpage",
            name="prompts",
            field=wagtail.fields.StreamField(
                [("prompt", wagtail.blocks.TextBlock())], blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="promptpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock(form_classname="title")),
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                ]
            ),
        ),
    ]
