# Generated by Django 5.0.2 on 2024-03-03 12:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("genai_app", "0004_promptpage_prompts_alter_promptpage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promptpage",
            name="prompts",
        ),
    ]
