# Generated by Django 5.0.2 on 2024-03-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genai_app", "0009_remove_formfield_form_intro_customformfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="customformfield",
            name="field_name",
            field=models.CharField(
                blank=True, max_length=254, verbose_name="Placeholder"
            ),
        ),
    ]
