# Generated by Django 5.0.2 on 2024-03-10 18:11

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("genai_app", "0012_mentorindexpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptpage",
            name="intro",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
