# Generated by Django 5.0.2 on 2024-03-12 17:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("genai_app", "0013_promptpage_intro"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterModelTable('ChatPage', 'genai_app_chatpage'),
                migrations.AlterModelTable('CustomForm', 'genai_app_customform'),
                migrations.AlterModelTable('CustomFormField', 'genai_app_customformfield'),
                migrations.AlterModelTable('CustomFormSubmission', 'genai_app_customformsubmission'),
                migrations.AlterModelTable('Dashboard', 'genai_app_dashboard'),
                migrations.AlterModelTable('FormField', 'genai_app_formfield'),
                migrations.AlterModelTable('MentorIndexPage', 'genai_app_mentorindexpage'),
                migrations.AlterModelTable('PromptPage', 'genai_app_promptpage'),
            ],
            database_operations=[]
        )
    ]
