# Generated by Django 5.0.2 on 2024-03-12 17:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("genai_app", "0014_auto_20240312_1729"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="chatpage",
            table=None,
        ),
        migrations.AlterModelTable(
            name="customform",
            table=None,
        ),
        migrations.AlterModelTable(
            name="customformfield",
            table=None,
        ),
        migrations.AlterModelTable(
            name="customformsubmission",
            table=None,
        ),
        migrations.AlterModelTable(
            name="dashboard",
            table=None,
        ),
        migrations.AlterModelTable(
            name="formfield",
            table=None,
        ),
        migrations.AlterModelTable(
            name="mentorindexpage",
            table=None,
        ),
        migrations.AlterModelTable(
            name="promptpage",
            table=None,
        ),
    ]
