# Generated by Django 5.0.3 on 2024-03-31 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_created_date_llmapikey_create_date'),
        ('genai_app', '0017_providerindexpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key_name', models.CharField(max_length=255)),
                ('provider', models.CharField(choices=[('OPENAI', 'OpenAI'), ('AWS_BEDROCK', 'AWS Bedrock')], max_length=20)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('val1', models.CharField(blank=True, max_length=255, null=True)),
                ('val2', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
            options={
                'ordering': ['organization', 'provider', 'api_key_name'],
                'indexes': [models.Index(fields=['organization', 'provider', 'api_key_name'], name='genai_app_o_organiz_6cd576_idx')],
            },
        ),
    ]
