# Generated by Django 5.0.3 on 2024-03-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genai_app', '0019_alter_orgprovider_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgprovider',
            name='val3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
