# Generated by Django 5.0.3 on 2024-03-31 18:13

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genai_app', '0020_orgprovider_val3'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerindexpage',
            name='aws_bedrock_instruction',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='providerindexpage',
            name='openai_instructions',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
