# Generated by Django 5.0.3 on 2024-03-31 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genai_app', '0021_providerindexpage_aws_bedrock_instruction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='providerindexpage',
            old_name='aws_bedrock_instruction',
            new_name='aws_bedrock_instructions',
        ),
    ]
